name: PROD-ACTION

on:
  push:
    branches: 
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Move to src folder
      run: cd ./src
    - name: install dependencies
      run: npm ci
    - name: run lint
      run: npm run lint
    - name: run tests
      run: npm run test